### ISSUE TITLE
Tela de Settings/Configurações

### ISSUE THREAD

**Issue by frankfhurt** [POSMOBILE/UPMOBILE2017#6]
Tela para definir as configurações do aplicativo

![screenshot_20171007-091530](https://user-images.githubusercontent.com/19345189/31307730-6b086caa-ab40-11e7-9206-284cc1e92a00.png)
![screenshot_20171007-091534](https://user-images.githubusercontent.com/19345189/31307731-6c6d0d80-ab40-11e7-8777-e2f9f9e61949.png)
![screenshot_20171007-091540](https://user-images.githubusercontent.com/19345189/31307732-6dc21612-ab40-11e7-9216-0e725ebc555b.png)

**Comment by frankfhurt** [comment]
Tela para definir as configurações do aplicativo

![screenshot_20171007-091530](https://user-images.githubusercontent.com/19345189/31307730-6b086caa-ab40-11e7-9206-284cc1e92a00.png)
![screenshot_20171007-091534](https://user-images.githubusercontent.com/19345189/31307731-6c6d0d80-ab40-11e7-8777-e2f9f9e61949.png)
![screenshot_20171007-091540](https://user-images.githubusercontent.com/19345189/31307732-6dc21612-ab40-11e7-9216-0e725ebc555b.png)

**Comment by jonathanmartinssandri** [comment]
Dupla: Franklyn Vieira e Jonathan Martins Sandri (Tela de Settings/Configurações)

**Comment by frankfhurt** [comment]
Tela Finalizada

![screenshot_1510530557](https://user-images.githubusercontent.com/19345189/32704853-8e451b08-c7f3-11e7-9a28-2c3524f61dc5.png)
![screenshot_1510530576](https://user-images.githubusercontent.com/19345189/32704854-90ad54be-c7f3-11e7-8257-6a3b8fe4b783.png)
![screenshot_1510530580](https://user-images.githubusercontent.com/19345189/32704858-949476a2-c7f3-11e7-916a-5c080a5366f4.png)
![screenshot_1510530584](https://user-images.githubusercontent.com/19345189/32704867-b1c25096-c7f3-11e7-970c-e2e1330742d0.png)
